/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#fcf9f8",
        "on-tertiary-fixed": "#201924",
        "inverse-primary": "#d7baff",
        "on-background": "#1c1b1b",
        "on-secondary-fixed-variant": "#6023a0",
        "surface-container-highest": "#e5e2e1",
        "surface-tint": "#7345b6",
        "on-error": "#ffffff",
        "on-primary-container": "#b889ff",
        "primary-fixed-dim": "#d7baff",
        "secondary-fixed-dim": "#dab9ff",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "primary": "#310065",
        "error": "#ba1a1a",
        "primary-fixed": "#eddcff",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#4d4450",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-container": "#a89cab",
        "outline-variant": "#cdc3d4",
        "surface-bright": "#fcf9f8",
        "surface-container": "#f0eded",
        "surface": "#fcf9f8",
        "tertiary-fixed": "#ecdeee",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#271f2a",
        "on-primary-fixed": "#280056",
        "on-primary-fixed-variant": "#5a2a9c",
        "secondary-fixed": "#efdbff",
        "outline": "#7c7483",
        "primary-container": "#4a148c",
        "surface-container-high": "#eae7e7",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#2b0053",
        "surface-variant": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "tertiary-container": "#3d3440",
        "secondary": "#7940ba",
        "tertiary-fixed-dim": "#cfc2d2",
        "on-secondary-container": "#4a008a",
        "secondary-container": "#b980fd",
        "surface-dim": "#dcd9d9",
        "on-surface-variant": "#4a4452"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1200px",
        "stack-md": "24px",
        "stack-sm": "12px",
        "margin-mobile": "16px",
        "unit": "8px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "stack-lg": "48px"
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "display-lg": ["Manrope"],
        "headline-md": ["Manrope"],
        "body-md": ["Inter"],
        "headline-lg": ["Manrope"],
        "headline-lg-mobile": ["Manrope"]
      },
      fontSize: {
        "label-sm": ["12px", {"lineHeight": "14px", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
